kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    role: ${TARGET_ROLE}
spec:
  selector:
    app: rabbitmq
    role: ${TARGET_ROLE}
  ports:
  - name: management
    port: 5672
    targetPort: 5672
  - name: dashboard
    port: 15672
    targetPort: 15672
