kind: Service
apiVersion: v1
metadata:
  name: turbine-stream-service
  labels:
    role: ${TARGET_ROLE}
spec:
  selector:
    app: turbine-stream-service
    role: ${TARGET_ROLE}
  ports:
  - port: 80
    targetPort: 80
  