security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /statistics
  port: 80

rates:
  url: https://api.exchangeratesapi.io