apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring

  template:
    metadata:
      labels:
        app: monitoring

    spec:
      containers:
      - name: ${MONITORING_IMAGE_NAME}
        image: "${ACR_REGISTRY}/${MONITORING_IMAGE_NAME}:${BUILD_NUMBER}"
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: admin
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: admin
          - name: STATISTICS_SERVICE_PASSWORD
            value: admin
          - name: ACCOUNT_SERVICE_PASSWORD
            value: admin
          - name: MONGODB_CONNECTION_STRING
            value: ${DB_CONNECTION_STRING}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: "${ACR_SECRET}"
  