apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-${TARGET_ROLE}
spec:
  selector:
    matchLabels:
      app: registry

  template:
    metadata:
      labels:
        app: registry
        role: ${TARGET_ROLE}

    spec:
      containers:
      - name: ${REGISTRY_IMAGE_NAME}
        image: "${ACR_REGISTRY}/${REGISTRY_IMAGE_NAME}:${BUILD_NUMBER}"
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: admin
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: admin
          - name: STATISTICS_SERVICE_PASSWORD
            value: admin
          - name: ACCOUNT_SERVICE_PASSWORD
            value: admin
          - name: MONGODB_CONNECTION_STRING
            value: ${DB_CONNECTION_STRING}
        ports:
        - containerPort: 8761
      imagePullSecrets:
      - name: "${ACR_SECRET}"
