apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statistics-service
spec:
  selector:
    matchLabels:
      app: statistics-service

  template:
    metadata:
      labels:
        app: statistics-service

    spec:
      containers:
      - name: ${STATISTICS_IMAGE_NAME}
        image: "${ACR_REGISTRY}/${STATISTICS_IMAGE_NAME}:${BUILD_NUMBER}"
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: admin
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: admin
          - name: STATISTICS_SERVICE_PASSWORD
            value: admin
          - name: ACCOUNT_SERVICE_PASSWORD
            value: admin
          - name: MONGODB_CONNECTION_STRING
            value: ${DB_CONNECTION_STRING}
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: "${ACR_SECRET}"
  